In [107]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings; 
warnings.simplefilter('ignore')
import pycountry
import plotly.express as px
import matplotlib.patches as mpatches
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import LinearSVC
import time
from sklearn.metrics import hamming_loss
from sklearn.metrics import jaccard_score
from sklearn.linear_model import SGDClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

In [108]:
data= pd.read_csv('final.csv')

In [109]:
data.shape

(194828, 28)

In [110]:
# Check for missing values
missing_values = data.isnull().sum()
print(missing_values)

Unnamed: 0                      0
Survey_No                  194828
Age                             2
Country                         2
Currency                        0
DevType                         0
EdLevel                         2
Ethnicity                       2
Gender                          2
Hobby                           2
JobSatisfaction                 2
JobSearchStatus             74459
JobStatus                   78802
OperatingSystem            116028
Profession                  78802
SalaryType                 116028
SalaryUSD                       2
UndergradMajor                  2
YearsCoding                116028
YearsCodingProf                 2
CompetenceLevel            120371
Employment                   3658
LanguageDesireNextYear1         2
LanguageDesireNextYear2     15067
LanguageDesireNextYear3     38383
LanguageWorkedWith1             2
LanguageWorkedWith2          8473
LanguageWorkedWith3         24686
dtype: int64

In [111]:
# Loop over columns and print unique values
for col in data.columns:
    print("Column:", col)
    print("Unique values:", data[col].unique())
    print("\n")

Column: Unnamed: 0
Unique values: [     1      2      3 ... 194826 194827 194828]


Column: Survey_No
Unique values: [nan]


Column: Age
Unique values: ['35 - 44 years old' '18 - 24 years old' '25 - 34 years old'
 '45 - 54 years old' '55 - 64 years old' 'Under 18 years old'
 '65 years or older' nan '28' '22' '30' '42' '24' '23' '21' '31' '20' '26'
 '29' '38' '47' '34' '32' '25' '35' '27' '44' '43' '37' '45' '18' '33'
 '19' '36' '16' '39' '41' '54' '49' '40' '56' '58' '46' '17' '51' '48'
 '57' '52' '50' '55' '15' '53' '59' '60' 27 32 41 23 29 59 39 26 21 56 34
 42 37 15 46 31 25 49 35 24 36 44 30 22 38 20 28 45 50 52 40 43 33 47 18
 48 19 51 16 54 17 55 57 53 58 60]


Column: Country
Unique values: ['United Kingdom' 'United States' 'South Africa' 'Nigeria' 'India'
 'Netherlands' 'Israel' 'Sweden' 'Australia' 'Greece' 'Poland' 'Belgium'
 'Argentina' 'Russian Federation' 'Indonesia' 'Germany' 'Ireland' 'France'
 'Ukraine' 'Denmark' 'China' 'Latvia' 'Algeria' 'Colombia' 'Japan'
 'Finland' 'Romania' 'Brazil' 'Bulgaria' 'Iran, Islamic Republic of...'
 'Pakistan' 'Canada' 'Portugal' 'Italy' 'New Zealand' 'Turkey'
 'Czech Republic' 'Austria' 'Egypt' 'Spain' 'Slovakia' 'Croatia' 'Mexico'
 'Norway' 'Switzerland' 'Armenia' 'Bangladesh' 'United Arab Emirates'
 'Singapore' 'Dominican Republic' 'Malaysia' 'Sri Lanka' 'Serbia'
 'Philippines' 'Botswana' 'Paraguay' 'Georgia' 'Uruguay' 'Belarus'
 'Lithuania' 'Thailand' 'Afghanistan' 'Estonia' 'Nepal' 'Hungary' 'Malta'
 'Myanmar' 'Costa Rica' 'Hong Kong (S.A.R.)' 'Bosnia and Herzegovina'
 'Ghana' 'Taiwan' 'Lebanon' 'Peru' 'Kenya' 'Chile' 'Viet Nam' 'Slovenia'
 'Uzbekistan' 'Republic of Korea' 'El Salvador' 'Cambodia' 'South Korea'
 'Venezuela, Bolivarian Republic of...' 'Tunisia' 'Saudi Arabia'
 'The former Yugoslav Republic of Macedonia' 'Morocco' 'Yemen' 'Uganda'
 'United Republic of Tanzania' 'Cuba' 'Ethiopia' 'Iceland' 'Oman'
 'Ecuador' 'Other Country (Not Listed Above)' 'Jordan'
 'Republic of Moldova' 'Honduras' 'Azerbaijan' 'Cyprus'
 'Syrian Arab Republic' 'Nicaragua' 'Kazakhstan' 'Kuwait' 'Cameroon'
 'Luxembourg' 'Albania' 'Bahrain' 'Zimbabwe' 'Guatemala' 'Mozambique'
 'Bolivia' 'Mauritius' 'Montenegro' 'Sudan' 'Maldives' 'Turkmenistan'
 'Panama' 'Lesotho' 'Somalia' 'Qatar' 'Mongolia' 'Kyrgyzstan' 'Swaziland'
 'Rwanda' 'Fiji' 'Marshall Islands' 'Iraq' 'Jamaica' 'Trinidad and Tobago'
 'Libyan Arab Jamahiriya' 'Madagascar' 'Namibia' 'Tajikistan' 'Malawi'
 'Bhutan' "Côte d'Ivoire" 'Andorra' 'Bahamas' 'Gambia' 'Sierra Leone'
 'Togo' 'Zambia' 'Benin' 'Democratic Republic of the Congo'
 'Congo, Republic of the...' 'Suriname' 'Senegal' 'Liechtenstein'
 'Barbados' 'Saint Lucia' 'Monaco' 'Guyana' 'Dominica' 'Eritrea' nan
 'Iran' 'Brunei Darussalam' 'Gabon' 'Guinea' 'Angola' 'Timor-Leste'
 'Djibouti' 'Burundi' 'Burkina Faso' 'Haiti'
 'Saint Vincent and the Grenadines' 'San Marino'
 "Lao People's Democratic Republic" 'Seychelles'
 "Democratic People's Republic of Korea" 'Chad' 'Mali' 'Nomadic'
 'Isle of Man' 'Kosovo' 'Niger']


Column: Currency
Unique values: ['British pounds sterling (£)' 'U.S. dollars ($)'
 'South African rands (R)' 'Euros (€)' 'Swedish kroner (SEK)'
 'Australian dollars (A$)' 'Indian rupees (₹)' 'Polish złoty (zł)'
 'Russian rubles (₽)' 'Danish krone (kr)' 'Chinese yuan renminbi (¥)'
 'Japanese yen (¥)' 'Brazilian reais (R$)' 'Canadian dollars (C$)'
 'Mexican pesos (MXN$)' 'Norwegian krone (kr)' 'Swiss francs'
 'Singapore dollars (S$)' 'Bitcoin (btc)']


Column: DevType
Unique values: ['Developer' 'Manager' 'Non Developer' 'Student' 'Non developer']


Column: EdLevel
Unique values: ['Bachelors' 'Associate' 'No Degree' 'Masters' 'Professional' 'Doctorate'
 nan]


Column: Ethnicity
Unique values: ['White or European descent' 'Black or African descent' 'South Asian'
 'Middle Eastern' 'Hispanic or Latino' 'East Asian' 'Native American' nan
 'White or of European descent' 'Black or of African descent'
 'Multiracial' 'Biracial' 'Indigenous' 'Southeast Asian']


Column: Gender
Unique values: ['Male' 'Non-binary' 'Female' nan]


Column: Hobby
Unique values: ['Yes' 'No' nan]


Column: JobSatisfaction
Unique values: ['Moderately dissatisfied' 'Moderately satisfied'
 'Neither satisfied nor dissatisfied' 'Slightly satisfied'
 'Extremely satisfied' 'Slightly dissatisfied' 'Extremely dissatisfied'
 nan 'Very satisfied' 'Very dissatisfied']


Column: JobSearchStatus
Unique values: ['I am actively looking for a job'
 'I’m not actively looking, but I am open to new opportunities'
 'I am not interested in new job opportunities' nan]


Column: JobStatus
Unique values: [nan 'Not seeking' 'Seeking'
 'I’m not actively looking, but I am open to new opportunities'
 'I am actively looking for a job'
 'I am not interested in new job opportunities']


Column: OperatingSystem
Unique values: ['Linux-based' 'Windows' 'MacOS' 'BSD/Unix' nan]


Column: Profession
Unique values: [nan 'Non developer' 'Developer' 'Novoice' 'Student' 'Ex-Developer']


Column: SalaryType
Unique values: ['Yearly' 'Monthly' 'Weekly' nan]


Column: SalaryUSD
Unique values: [ 70841.         153030.33333333 165809.20765661 ... 179004.
  18400.          85799.2       ]


Column: UndergradMajor
Unique values: ['Other Science' 'Computer Science' 'Arts and Science' 'Engineering'
 'No major' 'Business' 'Info Systems' 'Web Design/Dev' 'Math/Stat' nan
 'No Major']


Column: YearsCoding
Unique values: ['30 or more years' '24-26 years' '18-20 years' '6-8 years' '9-11 years'
 '0-2 years' '3-5 years' '15-17 years' '12-14 years' '21-23 years'
 '27-29 years' nan]


Column: YearsCodingProf
Unique values: ['18-20 years' '6-8 years' '12-14 years' '0-2 years' '3-5 years'
 '21-23 years' '24-26 years' '9-11 years' '15-17 years' '27-29 years'
 '30 or more years' nan '1.0' '9.0' '3.0' '4.0' '8.0' '2.0' '13.0' '18.0'
 '14.0' '22.0' '23.0' '5.0' '19.0' '20.0' '10.0' '7.0' '6.0' '12.0' '35.0'
 '31.0' '11.0' '27.0' '17.0' '25.0' '15.0' '16.0' '21.0' '29.0' '26.0'
 '30.0' '33.0' '28.0' '37.0' '34.0' '24.0' '38.0' '36.0' '32.0' '40.0'
 '39.0' '44.0' '42.0' 8.0 7.0 18.0 1.0 25.0 5.0 34.0 6.0 9.0 14.0 4.0 22.0
 3.0 2.0 27.0 12.0 15.0 21.0 10.0 28.0 19.0 17.0 11.0 20.0 24.0 16.0 32.0
 23.0 30.0 13.0 36.0 40.0 37.0 26.0 31.0 29.0 39.0 35.0 43.0 33.0 42.0
 46.0 38.0 41.0 8.74 45.0 47.0]


Column: CompetenceLevel
Unique values: [nan 'Average' 'A little below average' 'A little above average'
 'Far above average' 'Far below average']


Column: Employment
Unique values: ['Full-time' 'Part-time' 'Self-employed' nan 'Not employed' 'Student'
 'Not employed, and not looking for work' 'Retired']


Column: LanguageDesireNextYear1
Unique values: ['Go' 'C#' 'Assembly' 'C' 'Matlab' 'Erlang' 'Java' 'Python' 'PHP'
 'JavaScript' 'C++' 'SQL' 'CoffeeScript' 'Groovy' 'Ruby' 'Haskell' 'Swift'
 'Rust' 'Clojure' 'Julia' 'F#' 'Bash/Shell' 'TypeScript' 'Objective-C' 'R'
 'Kotlin' 'Perl' 'Lua' 'Scala' 'Delphi/Object Pascal' 'HTML' 'Hack'
 'Ocaml' 'VB.NET' 'CSS' 'VBA' 'Cobol' 'Visual Basic 6' nan 'Elixir'
 'HTML/CSS' 'Bash/Shell/PowerShell' 'Dart' 'Other(s):' 'WebAssembly']


Column: LanguageDesireNextYear2
Unique values: ['Python' 'JavaScript' 'C' 'Go' 'SQL' 'F#' 'R' 'C++' 'Bash/Shell' 'Scala'
 'HTML' 'Java' 'Clojure' 'Erlang' nan 'Haskell' 'PHP' 'Rust' 'C#' 'Perl'
 'Ruby' 'TypeScript' 'Objective-C' 'Kotlin' 'Hack' 'Swift' 'Ocaml'
 'Groovy' 'CSS' 'Julia' 'CoffeeScript' 'Matlab' 'Delphi/Object Pascal'
 'Lua' 'Cobol' 'VBA' 'VB.NET' 'Visual Basic 6' 'HTML/CSS'
 'Bash/Shell/PowerShell' 'Dart' 'Elixir' 'Other(s):' 'WebAssembly']


Column: LanguageDesireNextYear3
Unique values: [nan 'SQL' 'C++' 'Java' 'JavaScript' 'Kotlin' 'Python' 'Haskell' 'Go'
 'PHP' 'Swift' 'CSS' 'F#' 'Rust' 'C#' 'Scala' 'Julia' 'Ruby' 'HTML' 'R'
 'TypeScript' 'Objective-C' 'Groovy' 'Bash/Shell' 'Hack' 'Matlab' 'Lua'
 'Perl' 'VBA' 'Erlang' 'CoffeeScript' 'VB.NET' 'Ocaml' 'Clojure'
 'Delphi/Object Pascal' 'Cobol' 'Visual Basic 6' 'HTML/CSS' 'C' 'Elixir'
 'Other(s):' 'Dart' 'WebAssembly']


Column: LanguageWorkedWith1
Unique values: ['JavaScript' 'C#' 'C' 'Java' 'Assembly' 'Python' 'C++' 'PHP' 'SQL'
 'Erlang' 'Go' 'Ruby' 'Perl' 'Objective-C' 'Swift' 'CoffeeScript' 'Groovy'
 'Hack' 'F#' 'Haskell' 'Clojure' 'R' 'Ocaml' 'Delphi/Object Pascal' 'VBA'
 'Lua' 'Bash/Shell' 'VB.NET' 'Scala' 'Matlab' 'Julia' 'HTML' 'Rust'
 'Kotlin' 'TypeScript' 'Cobol' 'Visual Basic 6' 'CSS' nan 'HTML/CSS'
 'Bash/Shell/PowerShell' 'Elixir' 'Dart' 'Other(s):' 'WebAssembly']


Column: LanguageWorkedWith2
Unique values: ['Python' 'JavaScript' 'C++' 'HTML' 'TypeScript' 'CoffeeScript' nan 'SQL'
 'PHP' 'Java' 'F#' 'C' 'Go' 'Bash/Shell' 'Julia' 'R' 'Ruby' 'C#' 'Swift'
 'Clojure' 'Haskell' 'Perl' 'Objective-C' 'Kotlin' 'Groovy' 'Lua' 'VBA'
 'Erlang' 'Scala' 'Matlab' 'Delphi/Object Pascal' 'Visual Basic 6' 'Cobol'
 'Rust' 'Hack' 'VB.NET' 'CSS' 'Ocaml' 'HTML/CSS' 'Bash/Shell/PowerShell'
 'Other(s):' 'Dart' 'Elixir' 'WebAssembly']


Column: LanguageWorkedWith3
Unique values: ['Bash/Shell' 'SQL' 'Java' 'Python' 'CSS' 'HTML' 'Erlang' nan 'PHP' 'C#'
 'Go' 'JavaScript' 'Objective-C' 'C++' 'Groovy' 'Haskell' 'TypeScript'
 'Swift' 'Hack' 'Scala' 'R' 'Rust' 'Perl' 'Lua' 'CoffeeScript' 'Matlab'
 'Ruby' 'Julia' 'VBA' 'F#' 'Visual Basic 6' 'VB.NET' 'Kotlin'
 'Delphi/Object Pascal' 'Clojure' 'Cobol' 'Ocaml' 'HTML/CSS' 'C'
 'Other(s):' 'Dart' 'Elixir' 'WebAssembly']

In [112]:
data = pd.get_dummies(data, columns=['DevType', 'EdLevel', 'Ethnicity', 'Gender', 'Hobby', 'JobSatisfaction', 'JobSearchStatus', 'JobStatus', 'OperatingSystem', 'Profession', 'SalaryType', 'UndergradMajor', 'YearsCoding', 'CompetenceLevel', 'Employment',  'LanguageDesireNextYear2', 'LanguageDesireNextYear3', 'LanguageWorkedWith1', 'LanguageWorkedWith2', 'LanguageWorkedWith3'], prefix=['DevType', 'EdLevel', 'Ethnicity', 'Gender', 'Hobby', 'JobSatisfaction', 'JobSearchStatus', 'JobStatus', 'OperatingSystem', 'Profession', 'SalaryType', 'UndergradMajor', 'YearsCoding', 'CompetenceLevel', 'Employment', 'LanguageDesireNextYear2', 'LanguageDesireNextYear3', 'LanguageWorkedWith1', 'LanguageWorkedWith2', 'LanguageWorkedWith3'])

In [113]:
#data['Country'] = pd.factorize(data['Country'])[0]
#data['Currency'] = pd.factorize(data['Currency'])[0]

data['DevType'] = pd.factorize(data['DevType'])[0]
data['EdLevel'] = pd.factorize(data['EdLevel'])[0]
data['Ethnicity'] = pd.factorize(data['Ethnicity'])[0]
data['Gender'] = pd.factorize(data['Gender'])[0]
data['Hobby'] = pd.factorize(data['Hobby'])[0]
data['JobSatisfaction'] = pd.factorize(data['JobSatisfaction'])[0]
data['JobSearchStatus'] = pd.factorize(data['JobSearchStatus'])[0]
data['JobStatus'] = pd.factorize(data['JobStatus'])[0]
data['OperatingSystem'] = pd.factorize(data['OperatingSystem'])[0]
data['Profession'] = pd.factorize(data['Profession'])[0]
data['SalaryType'] = pd.factorize(data['SalaryType'])[0]
data['UndergradMajor'] = pd.factorize(data['UndergradMajor'])[0]
data['YearsCoding'] = pd.factorize(data['YearsCoding'])[0]
data['CompetenceLevel'] = pd.factorize(data['CompetenceLevel'])[0]
data['Employment'] = pd.factorize(data['Employment'])[0]

data['LanguageDesireNextYear2'] = pd.factorize(data['LanguageDesireNextYear2'])[0]
data['LanguageDesireNextYear3'] = pd.factorize(data['LanguageDesireNextYear3'])[0]
data['LanguageWorkedWith1'] = pd.factorize(data['LanguageWorkedWith1'])[0]
data['LanguageWorkedWith2'] = pd.factorize(data['LanguageWorkedWith2'])[0]
data['LanguageWorkedWith3'] = pd.factorize(data['LanguageWorkedWith3'])[0]

In [114]:
data = pd.get_dummies(data, columns=['Country'], prefix='Country')
data = pd.get_dummies(data, columns=['Currency'], prefix='Currency')

In [115]:
# Define a dictionary for the replacements
age_dict = {
    '35 - 44 years old': 40,
    '18 - 24 years old': 20,
    '25 - 34 years old': 30,
    '45 - 54 years old': 50,
    '55 - 64 years old': 58,
    'Under 18 years old': 18,
    '65 years or older': 69
}

# Use the replace() function to replace the age ranges
data['Age'] = data['Age'].replace(age_dict)

In [116]:
 # Define a dictionary for the replacements
age_dict = {
    '18-20 years': 18, 
    '6-8 years': 7, 
    '12-14 years': 12, 
    '0-2 years':1, 
    '3-5 years': 4,
    '21-23 years': 22, 
    '24-26 years':25, 
    '9-11 years':10, 
    '15-17 years':15, 
    '27-29 years': 28,
    '30 or more years':35
}

# Use the replace() function to replace the age ranges
data['YearsCodingProf'] = data['YearsCodingProf'].replace(age_dict)

In [117]:
data

,Unnamed: 0,Survey_No,Age,SalaryUSD,YearsCodingProf,LanguageDesireNextYear1,DevType_Developer,DevType_Manager,DevType_Non Developer,DevType_Non developer,...,Currency_Japanese yen (¥),Currency_Mexican pesos (MXN$),Currency_Norwegian krone (kr),Currency_Polish złoty (zł),Currency_Russian rubles (₽),Currency_Singapore dollars (S$),Currency_South African rands (R),Currency_Swedish kroner (SEK),Currency_Swiss francs,Currency_U.S. dollars ($)
0,1,NaN,40,70841.000000,18,Go,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,NaN,40,153030.333333,7,Go,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,3,NaN,40,165809.207657,12,C#,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,4,NaN,20,21426.000000,1,Assembly,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,5,NaN,20,41671.000000,4,C#,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194823,194824,NaN,21,8318.666667,8.74,Go,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
194824,194825,NaN,21,8318.666667,8.74,Java,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
194825,194826,NaN,21,5268.000000,8.74,Dart,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
194826,194827,NaN,22,9612.000000,3.0,TypeScript,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
194827,194828,NaN,41,200.000000,20.0,Go,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [118]:
# Loop over columns and print unique values
for col in data.columns:
    print("Column:", col)
    print("Unique values:", data[col].unique())
    print("\n")

Column: Unnamed: 0
Unique values: [     1      2      3 ... 194826 194827 194828]


Column: Survey_No
Unique values: [nan]


Column: Age
Unique values: [40 20 30 50 58 18 69 nan '28' '22' '30' '42' '24' '23' '21' '31' '20'
 '26' '29' '38' '47' '34' '32' '25' '35' '27' '44' '43' '37' '45' '18'
 '33' '19' '36' '16' '39' '41' '54' '49' '40' '56' '58' '46' '17' '51'
 '48' '57' '52' '50' '55' '15' '53' '59' '60' 27 32 41 23 29 59 39 26 21
 56 34 42 37 15 46 31 25 49 35 24 36 44 22 38 28 45 52 43 33 47 48 19 51
 16 54 17 55 57 53 60]


Column: SalaryUSD
Unique values: [ 70841.         153030.33333333 165809.20765661 ... 179004.
  18400.          85799.2       ]


Column: YearsCodingProf
Unique values: [18 7 12 1 4 22 25 10 15 28 35 nan '1.0' '9.0' '3.0' '4.0' '8.0' '2.0'
 '13.0' '18.0' '14.0' '22.0' '23.0' '5.0' '19.0' '20.0' '10.0' '7.0' '6.0'
 '12.0' '35.0' '31.0' '11.0' '27.0' '17.0' '25.0' '15.0' '16.0' '21.0'
 '29.0' '26.0' '30.0' '33.0' '28.0' '37.0' '34.0' '24.0' '38.0' '36.0'
 '32.0' '40.0' '39.0' '44.0' '42.0' 8.0 5.0 34.0 6.0 9.0 14.0 3.0 2.0 27.0
 21.0 19.0 17.0 11.0 20.0 24.0 16.0 32.0 23.0 30.0 13.0 36.0 40.0 37.0
 26.0 31.0 29.0 39.0 43.0 33.0 42.0 46.0 38.0 41.0 8.74 45.0 47.0]


Column: LanguageDesireNextYear1
Unique values: ['Go' 'C#' 'Assembly' 'C' 'Matlab' 'Erlang' 'Java' 'Python' 'PHP'
 'JavaScript' 'C++' 'SQL' 'CoffeeScript' 'Groovy' 'Ruby' 'Haskell' 'Swift'
 'Rust' 'Clojure' 'Julia' 'F#' 'Bash/Shell' 'TypeScript' 'Objective-C' 'R'
 'Kotlin' 'Perl' 'Lua' 'Scala' 'Delphi/Object Pascal' 'HTML' 'Hack'
 'Ocaml' 'VB.NET' 'CSS' 'VBA' 'Cobol' 'Visual Basic 6' nan 'Elixir'
 'HTML/CSS' 'Bash/Shell/PowerShell' 'Dart' 'Other(s):' 'WebAssembly']


Column: DevType_Developer
Unique values: [ True False]


Column: DevType_Manager
Unique values: [False  True]


Column: DevType_Non Developer
Unique values: [False  True]


Column: DevType_Non developer
Unique values: [False  True]


Column: DevType_Student
Unique values: [False  True]


Column: EdLevel_Associate
Unique values: [False  True]


Column: EdLevel_Bachelors
Unique values: [ True False]


Column: EdLevel_Doctorate
Unique values: [False  True]


Column: EdLevel_Masters
Unique values: [False  True]


Column: EdLevel_No Degree
Unique values: [False  True]


Column: EdLevel_Professional
Unique values: [False  True]


Column: Ethnicity_Biracial
Unique values: [False  True]


Column: Ethnicity_Black or African descent
Unique values: [False  True]


Column: Ethnicity_Black or of African descent
Unique values: [False  True]


Column: Ethnicity_East Asian
Unique values: [False  True]


Column: Ethnicity_Hispanic or Latino
Unique values: [False  True]


Column: Ethnicity_Indigenous
Unique values: [False  True]


Column: Ethnicity_Middle Eastern
Unique values: [False  True]


Column: Ethnicity_Multiracial
Unique values: [False  True]


Column: Ethnicity_Native American
Unique values: [False  True]


Column: Ethnicity_South Asian
Unique values: [False  True]


Column: Ethnicity_Southeast Asian
Unique values: [False  True]


Column: Ethnicity_White or European descent
Unique values: [ True False]


Column: Ethnicity_White or of European descent
Unique values: [False  True]


Column: Gender_Female
Unique values: [False  True]


Column: Gender_Male
Unique values: [ True False]


Column: Gender_Non-binary
Unique values: [False  True]


Column: Hobby_No
Unique values: [False  True]


Column: Hobby_Yes
Unique values: [ True False]


Column: JobSatisfaction_Extremely dissatisfied
Unique values: [False  True]


Column: JobSatisfaction_Extremely satisfied
Unique values: [False  True]


Column: JobSatisfaction_Moderately dissatisfied
Unique values: [ True False]


Column: JobSatisfaction_Moderately satisfied
Unique values: [False  True]


Column: JobSatisfaction_Neither satisfied nor dissatisfied
Unique values: [False  True]


Column: JobSatisfaction_Slightly dissatisfied
Unique values: [False  True]


Column: JobSatisfaction_Slightly satisfied
Unique values: [False  True]


Column: JobSatisfaction_Very dissatisfied
Unique values: [False  True]


Column: JobSatisfaction_Very satisfied
Unique values: [False  True]


Column: JobSearchStatus_I am actively looking for a job
Unique values: [ True False]


Column: JobSearchStatus_I am not interested in new job opportunities
Unique values: [False  True]


Column: JobSearchStatus_I’m not actively looking, but I am open to new opportunities
Unique values: [False  True]


Column: JobStatus_I am actively looking for a job
Unique values: [False  True]


Column: JobStatus_I am not interested in new job opportunities
Unique values: [False  True]


Column: JobStatus_I’m not actively looking, but I am open to new opportunities
Unique values: [False  True]


Column: JobStatus_Not seeking
Unique values: [False  True]


Column: JobStatus_Seeking
Unique values: [False  True]


Column: OperatingSystem_BSD/Unix
Unique values: [False  True]


Column: OperatingSystem_Linux-based
Unique values: [ True False]


Column: OperatingSystem_MacOS
Unique values: [False  True]


Column: OperatingSystem_Windows
Unique values: [False  True]


Column: Profession_Developer
Unique values: [False  True]


Column: Profession_Ex-Developer
Unique values: [False  True]


Column: Profession_Non developer
Unique values: [False  True]


Column: Profession_Novoice
Unique values: [False  True]


Column: Profession_Student
Unique values: [False  True]


Column: SalaryType_Monthly
Unique values: [False  True]


Column: SalaryType_Weekly
Unique values: [False  True]


Column: SalaryType_Yearly
Unique values: [ True False]


Column: UndergradMajor_Arts and Science
Unique values: [False  True]


Column: UndergradMajor_Business
Unique values: [False  True]


Column: UndergradMajor_Computer Science
Unique values: [False  True]


Column: UndergradMajor_Engineering
Unique values: [False  True]


Column: UndergradMajor_Info Systems
Unique values: [False  True]


Column: UndergradMajor_Math/Stat
Unique values: [False  True]


Column: UndergradMajor_No Major
Unique values: [False  True]


Column: UndergradMajor_No major
Unique values: [False  True]


Column: UndergradMajor_Other Science
Unique values: [ True False]


Column: UndergradMajor_Web Design/Dev
Unique values: [False  True]


Column: YearsCoding_0-2 years
Unique values: [False  True]


Column: YearsCoding_12-14 years
Unique values: [False  True]


Column: YearsCoding_15-17 years
Unique values: [False  True]


Column: YearsCoding_18-20 years
Unique values: [False  True]


Column: YearsCoding_21-23 years
Unique values: [False  True]


Column: YearsCoding_24-26 years
Unique values: [False  True]


Column: YearsCoding_27-29 years
Unique values: [False  True]


Column: YearsCoding_3-5 years
Unique values: [False  True]


Column: YearsCoding_30 or more years
Unique values: [ True False]


Column: YearsCoding_6-8 years
Unique values: [False  True]


Column: YearsCoding_9-11 years
Unique values: [False  True]


Column: CompetenceLevel_A little above average
Unique values: [False  True]


Column: CompetenceLevel_A little below average
Unique values: [False  True]


Column: CompetenceLevel_Average
Unique values: [False  True]


Column: CompetenceLevel_Far above average
Unique values: [False  True]


Column: CompetenceLevel_Far below average
Unique values: [False  True]


Column: Employment_Full-time
Unique values: [ True False]


Column: Employment_Not employed
Unique values: [False  True]


Column: Employment_Not employed, and not looking for work
Unique values: [False  True]


Column: Employment_Part-time
Unique values: [False  True]


Column: Employment_Retired
Unique values: [False  True]


Column: Employment_Self-employed
Unique values: [False  True]


Column: Employment_Student
Unique values: [False  True]


Column: LanguageDesireNextYear2_Bash/Shell
Unique values: [False  True]


Column: LanguageDesireNextYear2_Bash/Shell/PowerShell
Unique values: [False  True]


Column: LanguageDesireNextYear2_C
Unique values: [False  True]


Column: LanguageDesireNextYear2_C#
Unique values: [False  True]


Column: LanguageDesireNextYear2_C++
Unique values: [False  True]


Column: LanguageDesireNextYear2_CSS
Unique values: [False  True]


Column: LanguageDesireNextYear2_Clojure
Unique values: [False  True]


Column: LanguageDesireNextYear2_Cobol
Unique values: [False  True]


Column: LanguageDesireNextYear2_CoffeeScript
Unique values: [False  True]


Column: LanguageDesireNextYear2_Dart
Unique values: [False  True]


Column: LanguageDesireNextYear2_Delphi/Object Pascal
Unique values: [False  True]


Column: LanguageDesireNextYear2_Elixir
Unique values: [False  True]


Column: LanguageDesireNextYear2_Erlang
Unique values: [False  True]


Column: LanguageDesireNextYear2_F#
Unique values: [False  True]


Column: LanguageDesireNextYear2_Go
Unique values: [False  True]


Column: LanguageDesireNextYear2_Groovy
Unique values: [False  True]


Column: LanguageDesireNextYear2_HTML
Unique values: [False  True]


Column: LanguageDesireNextYear2_HTML/CSS
Unique values: [False  True]


Column: LanguageDesireNextYear2_Hack
Unique values: [False  True]


Column: LanguageDesireNextYear2_Haskell
Unique values: [False  True]


Column: LanguageDesireNextYear2_Java
Unique values: [False  True]


Column: LanguageDesireNextYear2_JavaScript
Unique values: [False  True]


Column: LanguageDesireNextYear2_Julia
Unique values: [False  True]


Column: LanguageDesireNextYear2_Kotlin
Unique values: [False  True]


Column: LanguageDesireNextYear2_Lua
Unique values: [False  True]


Column: LanguageDesireNextYear2_Matlab
Unique values: [False  True]


Column: LanguageDesireNextYear2_Objective-C
Unique values: [False  True]


Column: LanguageDesireNextYear2_Ocaml
Unique values: [False  True]


Column: LanguageDesireNextYear2_Other(s):
Unique values: [False  True]


Column: LanguageDesireNextYear2_PHP
Unique values: [False  True]


Column: LanguageDesireNextYear2_Perl
Unique values: [False  True]


Column: LanguageDesireNextYear2_Python
Unique values: [ True False]


Column: LanguageDesireNextYear2_R
Unique values: [False  True]


Column: LanguageDesireNextYear2_Ruby
Unique values: [False  True]


Column: LanguageDesireNextYear2_Rust
Unique values: [False  True]


Column: LanguageDesireNextYear2_SQL
Unique values: [False  True]


Column: LanguageDesireNextYear2_Scala
Unique values: [False  True]


Column: LanguageDesireNextYear2_Swift
Unique values: [False  True]


Column: LanguageDesireNextYear2_TypeScript
Unique values: [False  True]


Column: LanguageDesireNextYear2_VB.NET
Unique values: [False  True]


Column: LanguageDesireNextYear2_VBA
Unique values: [False  True]


Column: LanguageDesireNextYear2_Visual Basic 6
Unique values: [False  True]


Column: LanguageDesireNextYear2_WebAssembly
Unique values: [False  True]


Column: LanguageDesireNextYear3_Bash/Shell
Unique values: [False  True]


Column: LanguageDesireNextYear3_C
Unique values: [False  True]


Column: LanguageDesireNextYear3_C#
Unique values: [False  True]


Column: LanguageDesireNextYear3_C++
Unique values: [False  True]


Column: LanguageDesireNextYear3_CSS
Unique values: [False  True]


Column: LanguageDesireNextYear3_Clojure
Unique values: [False  True]


Column: LanguageDesireNextYear3_Cobol
Unique values: [False  True]


Column: LanguageDesireNextYear3_CoffeeScript
Unique values: [False  True]


Column: LanguageDesireNextYear3_Dart
Unique values: [False  True]


Column: LanguageDesireNextYear3_Delphi/Object Pascal
Unique values: [False  True]


Column: LanguageDesireNextYear3_Elixir
Unique values: [False  True]


Column: LanguageDesireNextYear3_Erlang
Unique values: [False  True]


Column: LanguageDesireNextYear3_F#
Unique values: [False  True]


Column: LanguageDesireNextYear3_Go
Unique values: [False  True]


Column: LanguageDesireNextYear3_Groovy
Unique values: [False  True]


Column: LanguageDesireNextYear3_HTML
Unique values: [False  True]


Column: LanguageDesireNextYear3_HTML/CSS
Unique values: [False  True]


Column: LanguageDesireNextYear3_Hack
Unique values: [False  True]


Column: LanguageDesireNextYear3_Haskell
Unique values: [False  True]


Column: LanguageDesireNextYear3_Java
Unique values: [False  True]


Column: LanguageDesireNextYear3_JavaScript
Unique values: [False  True]


Column: LanguageDesireNextYear3_Julia
Unique values: [False  True]


Column: LanguageDesireNextYear3_Kotlin
Unique values: [False  True]


Column: LanguageDesireNextYear3_Lua
Unique values: [False  True]


Column: LanguageDesireNextYear3_Matlab
Unique values: [False  True]


Column: LanguageDesireNextYear3_Objective-C
Unique values: [False  True]


Column: LanguageDesireNextYear3_Ocaml
Unique values: [False  True]


Column: LanguageDesireNextYear3_Other(s):
Unique values: [False  True]


Column: LanguageDesireNextYear3_PHP
Unique values: [False  True]


Column: LanguageDesireNextYear3_Perl
Unique values: [False  True]


Column: LanguageDesireNextYear3_Python
Unique values: [False  True]


Column: LanguageDesireNextYear3_R
Unique values: [False  True]


Column: LanguageDesireNextYear3_Ruby
Unique values: [False  True]


Column: LanguageDesireNextYear3_Rust
Unique values: [False  True]


Column: LanguageDesireNextYear3_SQL
Unique values: [False  True]


Column: LanguageDesireNextYear3_Scala
Unique values: [False  True]


Column: LanguageDesireNextYear3_Swift
Unique values: [False  True]


Column: LanguageDesireNextYear3_TypeScript
Unique values: [False  True]


Column: LanguageDesireNextYear3_VB.NET
Unique values: [False  True]


Column: LanguageDesireNextYear3_VBA
Unique values: [False  True]


Column: LanguageDesireNextYear3_Visual Basic 6
Unique values: [False  True]


Column: LanguageDesireNextYear3_WebAssembly
Unique values: [False  True]


Column: LanguageWorkedWith1_Assembly
Unique values: [False  True]


Column: LanguageWorkedWith1_Bash/Shell
Unique values: [False  True]


Column: LanguageWorkedWith1_Bash/Shell/PowerShell
Unique values: [False  True]


Column: LanguageWorkedWith1_C
Unique values: [False  True]


Column: LanguageWorkedWith1_C#
Unique values: [False  True]


Column: LanguageWorkedWith1_C++
Unique values: [False  True]


Column: LanguageWorkedWith1_CSS
Unique values: [False  True]


Column: LanguageWorkedWith1_Clojure
Unique values: [False  True]


Column: LanguageWorkedWith1_Cobol
Unique values: [False  True]


Column: LanguageWorkedWith1_CoffeeScript
Unique values: [False  True]


Column: LanguageWorkedWith1_Dart
Unique values: [False  True]


Column: LanguageWorkedWith1_Delphi/Object Pascal
Unique values: [False  True]


Column: LanguageWorkedWith1_Elixir
Unique values: [False  True]


Column: LanguageWorkedWith1_Erlang
Unique values: [False  True]


Column: LanguageWorkedWith1_F#
Unique values: [False  True]


Column: LanguageWorkedWith1_Go
Unique values: [False  True]


Column: LanguageWorkedWith1_Groovy
Unique values: [False  True]


Column: LanguageWorkedWith1_HTML
Unique values: [False  True]


Column: LanguageWorkedWith1_HTML/CSS
Unique values: [False  True]


Column: LanguageWorkedWith1_Hack
Unique values: [False  True]


Column: LanguageWorkedWith1_Haskell
Unique values: [False  True]


Column: LanguageWorkedWith1_Java
Unique values: [False  True]


Column: LanguageWorkedWith1_JavaScript
Unique values: [ True False]


Column: LanguageWorkedWith1_Julia
Unique values: [False  True]


Column: LanguageWorkedWith1_Kotlin
Unique values: [False  True]


Column: LanguageWorkedWith1_Lua
Unique values: [False  True]


Column: LanguageWorkedWith1_Matlab
Unique values: [False  True]


Column: LanguageWorkedWith1_Objective-C
Unique values: [False  True]


Column: LanguageWorkedWith1_Ocaml
Unique values: [False  True]


Column: LanguageWorkedWith1_Other(s):
Unique values: [False  True]


Column: LanguageWorkedWith1_PHP
Unique values: [False  True]


Column: LanguageWorkedWith1_Perl
Unique values: [False  True]


Column: LanguageWorkedWith1_Python
Unique values: [False  True]


Column: LanguageWorkedWith1_R
Unique values: [False  True]


Column: LanguageWorkedWith1_Ruby
Unique values: [False  True]


Column: LanguageWorkedWith1_Rust
Unique values: [False  True]


Column: LanguageWorkedWith1_SQL
Unique values: [False  True]


Column: LanguageWorkedWith1_Scala
Unique values: [False  True]


Column: LanguageWorkedWith1_Swift
Unique values: [False  True]


Column: LanguageWorkedWith1_TypeScript
Unique values: [False  True]


Column: LanguageWorkedWith1_VB.NET
Unique values: [False  True]


Column: LanguageWorkedWith1_VBA
Unique values: [False  True]


Column: LanguageWorkedWith1_Visual Basic 6
Unique values: [False  True]


Column: LanguageWorkedWith1_WebAssembly
Unique values: [False  True]


Column: LanguageWorkedWith2_Bash/Shell
Unique values: [False  True]


Column: LanguageWorkedWith2_Bash/Shell/PowerShell
Unique values: [False  True]


Column: LanguageWorkedWith2_C
Unique values: [False  True]


Column: LanguageWorkedWith2_C#
Unique values: [False  True]


Column: LanguageWorkedWith2_C++
Unique values: [False  True]


Column: LanguageWorkedWith2_CSS
Unique values: [False  True]


Column: LanguageWorkedWith2_Clojure
Unique values: [False  True]


Column: LanguageWorkedWith2_Cobol
Unique values: [False  True]


Column: LanguageWorkedWith2_CoffeeScript
Unique values: [False  True]


Column: LanguageWorkedWith2_Dart
Unique values: [False  True]


Column: LanguageWorkedWith2_Delphi/Object Pascal
Unique values: [False  True]


Column: LanguageWorkedWith2_Elixir
Unique values: [False  True]


Column: LanguageWorkedWith2_Erlang
Unique values: [False  True]


Column: LanguageWorkedWith2_F#
Unique values: [False  True]


Column: LanguageWorkedWith2_Go
Unique values: [False  True]


Column: LanguageWorkedWith2_Groovy
Unique values: [False  True]


Column: LanguageWorkedWith2_HTML
Unique values: [False  True]


Column: LanguageWorkedWith2_HTML/CSS
Unique values: [False  True]


Column: LanguageWorkedWith2_Hack
Unique values: [False  True]


Column: LanguageWorkedWith2_Haskell
Unique values: [False  True]


Column: LanguageWorkedWith2_Java
Unique values: [False  True]


Column: LanguageWorkedWith2_JavaScript
Unique values: [False  True]


Column: LanguageWorkedWith2_Julia
Unique values: [False  True]


Column: LanguageWorkedWith2_Kotlin
Unique values: [False  True]


Column: LanguageWorkedWith2_Lua
Unique values: [False  True]


Column: LanguageWorkedWith2_Matlab
Unique values: [False  True]


Column: LanguageWorkedWith2_Objective-C
Unique values: [False  True]


Column: LanguageWorkedWith2_Ocaml
Unique values: [False  True]


Column: LanguageWorkedWith2_Other(s):
Unique values: [False  True]


Column: LanguageWorkedWith2_PHP
Unique values: [False  True]


Column: LanguageWorkedWith2_Perl
Unique values: [False  True]


Column: LanguageWorkedWith2_Python
Unique values: [ True False]


Column: LanguageWorkedWith2_R
Unique values: [False  True]


Column: LanguageWorkedWith2_Ruby
Unique values: [False  True]


Column: LanguageWorkedWith2_Rust
Unique values: [False  True]


Column: LanguageWorkedWith2_SQL
Unique values: [False  True]


Column: LanguageWorkedWith2_Scala
Unique values: [False  True]


Column: LanguageWorkedWith2_Swift
Unique values: [False  True]


Column: LanguageWorkedWith2_TypeScript
Unique values: [False  True]


Column: LanguageWorkedWith2_VB.NET
Unique values: [False  True]


Column: LanguageWorkedWith2_VBA
Unique values: [False  True]


Column: LanguageWorkedWith2_Visual Basic 6
Unique values: [False  True]


Column: LanguageWorkedWith2_WebAssembly
Unique values: [False  True]


Column: LanguageWorkedWith3_Bash/Shell
Unique values: [ True False]


Column: LanguageWorkedWith3_C
Unique values: [False  True]


Column: LanguageWorkedWith3_C#
Unique values: [False  True]


Column: LanguageWorkedWith3_C++
Unique values: [False  True]


Column: LanguageWorkedWith3_CSS
Unique values: [False  True]


Column: LanguageWorkedWith3_Clojure
Unique values: [False  True]


Column: LanguageWorkedWith3_Cobol
Unique values: [False  True]


Column: LanguageWorkedWith3_CoffeeScript
Unique values: [False  True]



In [119]:
data.rename(columns={'Unnamed: 0': 'Survey'}, inplace=True)
data.drop('Survey_No', axis=1, inplace=True)

# Check for missing values
missing_values = data.isnull().sum()
print(missing_values)

Survey                              0
Age                                 2
SalaryUSD                           2
YearsCodingProf                     2
LanguageDesireNextYear1             2
                                   ..
Currency_Singapore dollars (S$)     0
Currency_South African rands (R)    0
Currency_Swedish kroner (SEK)       0
Currency_Swiss francs               0
Currency_U.S. dollars ($)           0
Length: 507, dtype: int64

In [142]:
# Drop NaN values from both X and y_train_encoded
data = data.dropna(subset=['Age', 'SalaryUSD', 'YearsCodingProf'])
y = data['LanguageDesireNextYear1']
X = data.drop('LanguageDesireNextYear1', axis=1)


# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [121]:
# Create a LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the target variable
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

In [122]:
missing_values = data.isnull().sum()
print(missing_values)

Survey                              0
Age                                 0
SalaryUSD                           0
YearsCodingProf                     0
LanguageDesireNextYear1             0
                                   ..
Currency_Singapore dollars (S$)     0
Currency_South African rands (R)    0
Currency_Swedish kroner (SEK)       0
Currency_Swiss francs               0
Currency_U.S. dollars ($)           0
Length: 507, dtype: int64

In [126]:
print(y_test_encoded.dtype)

int32

In [124]:
print(X.shape)
print(y_train_encoded.shape)

(194826, 506)
(155860,)

In [155]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Assuming X_train is your feature matrix
#X_train, X_test, _, y_test = train_test_split(X, y_train_encoded, test_size=0.2, random_state=42)

# Create a Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train_encoded)

# Make predictions
y_pred = model.predict(X_test)




# Inverse transform to get original labels
# Inverse transform to get original labels
#y_pred_original = label_encoder.inverse_transform(y_pred.astype(int))

# Evaluate the model
model

LinearRegression()

In [156]:
# Make predictions on the test data
predictions = model.predict(X_test)

In [157]:
y_pred

array([22.41244482,  2.07144011, 18.96989944, ..., 23.95529246,
       12.67490836,  7.65472795])

In [158]:
y_test_encoded

array([24,  2,  4, ..., 21,  4,  4])

In [159]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Calculate the metrics
mse = mean_squared_error(y_test_encoded, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test_encoded, y_pred)
r2 = r2_score(y_test_encoded, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'Root Mean Squared Error: {rmse}')
print(f'Mean Absolute Error: {mae}')
print(f'R-squared: {r2}')

Mean Squared Error: 38.93165066131709
Root Mean Squared Error: 6.239523271958932
Mean Absolute Error: 4.5342023276839365
R-squared: 0.6129071268598328